export const kanji = [
  {
    kanji: "人",
    onyomi: ["ジン", "ニン"],
    kunyomi: ["ひと", " -り", "-と"],
    meaning: "person",
  },
  {
    kanji: "日",
    onyomi: ["ニチ", "ジツ"],
    kunyomi: ["ひ", "-び", "-か"],
    meaning: "day/sun",
  },
  {
    kanji: "一",
    onyomi: ["イチ", "イツ"],
    kunyomi: ["ひと-", " ひと.つ"],
    meaning: "one/first",
  },
  {
    kanji: "大",
    onyomi: ["ダイ", "タイ"],
    kunyomi: ["おお-", " おお.きい", "-おお.いに"],
    meaning: "large/big",
  },
  {
    kanji: "年",
    onyomi: ["ネン"],
    kunyomi: ["とし"],
    meaning: "year",
  },
  {
    kanji: "本",
    onyomi: ["ホン"],
    kunyomi: ["もと"],
    meaning: "book/origin",
  },
  {
    kanji: "子",
    onyomi: ["シ", "ス", "ツ"],
    kunyomi: ["こ", " -こ", "ね"],
    meaning: "child",
  },
  {
    kanji: "見",
    onyomi: ["ケン"],
    kunyomi: ["み.る", "み.える", "み.せる"],
    meaning: "to see",
  },
  {
    kanji: "国",
    onyomi: ["コク"],
    kunyomi: ["くに"],
    meaning: "country",
  },
  {
    kanji: "言",
    onyomi: ["ゲン", "ゴン"],
    kunyomi: ["い.う", "こと"],
    meaning: "say/word",
  },
  {
    kanji: "水",
    onyomi: ["スイ"],
    kunyomi: ["みず", "みず-"],
    meaning: "water",
  },
  {
    kanji: "火",
    onyomi: ["カ"],
    kunyomi: ["ひ", "-び", "ほ-"],
    meaning: "fire",
  },
  {
    kanji: "手",
    onyomi: ["シュ", "ズ"],
    kunyomi: ["て", "て-", "た-"],
    meaning: "hand",
  },
  {
    kanji: "自",
    onyomi: ["ジ", "シ"],
    kunyomi: ["みずか.ら", "おの.ずから", "おの.ずと"],
    meaning: "self/oneself",
  },
  {
    kanji: "事",
    onyomi: ["ジ", "ズ"],
    kunyomi: ["こと", "つか.う", "つか.える"],
    meaning: "thing",
  },
  {
    kanji: "目",
    onyomi: ["モク", "ボク"],
    kunyomi: ["め", "-め", "ま-"],
    meaning: "eye",
  },
  {
    kanji: "入",
    onyomi: ["ニュウ", "ジュ"],
    kunyomi: ["い.る", "-い.る", "-い.り", "い.れる"],
    meaning: "eye",
  },
  {
    kanji: "山",
    onyomi: ["サン", "セン"],
    kunyomi: ["やま"],
    meaning: "eye",
  },
  {
    kanji: "金",
    onyomi: ["キン", "コン", "ゴン"],
    kunyomi: ["かね", "かな-", "-がね"],
    meaning: "eye",
  },
  {
    kanji: "女",
    onyomi: ["ジョ", "ニョ", "ニョウ"],
    kunyomi: ["おんな", "め"],
    meaning: "eye",
  },
];
